//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunSimioSchedule.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Event.csv")]
        public string EventFile {
            get {
                return ((string)(this["EventFile"]));
            }
            set {
                this["EventFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RunStatus.txt")]
        public string StatusFile {
            get {
                return ((string)(this["StatusFile"]));
            }
            set {
                this["StatusFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveProject {
            get {
                return ((bool)(this["SaveProject"]));
            }
            set {
                this["SaveProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearStatusBeforeEachRun {
            get {
                return ((bool)(this["ClearStatusBeforeEachRun"]));
            }
            set {
                this["ClearStatusBeforeEachRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteStatusBeforeEachRun {
            get {
                return ((bool)(this["DeleteStatusBeforeEachRun"]));
            }
            set {
                this["DeleteStatusBeforeEachRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchedulingTest1.spfx")]
        public string SimioProjectFile {
            get {
                return ((string)(this["SimioProjectFile"]));
            }
            set {
                this["SimioProjectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExportSchedule.xml")]
        public string ExportScheduleFile {
            get {
                return ((string)(this["ExportScheduleFile"]));
            }
            set {
                this["ExportScheduleFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Model")]
        public string ModelName {
            get {
                return ((string)(this["ModelName"]));
            }
            set {
                this["ModelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunPlan {
            get {
                return ((bool)(this["RunPlan"]));
            }
            set {
                this["RunPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunRiskAnalysis {
            get {
                return ((bool)(this["RunRiskAnalysis"]));
            }
            set {
                this["RunRiskAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportSchedule {
            get {
                return ((bool)(this["ExportSchedule"]));
            }
            set {
                this["ExportSchedule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\temp\\\\RunSimioScheduleTest")]
        public string RootFolder {
            get {
                return ((string)(this["RootFolder"]));
            }
            set {
                this["RootFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchedulingDiscretePartProductionWithOnRunEndingExport.spfx")]
        public string SaveThisStuff {
            get {
                return ((string)(this["SaveThisStuff"]));
            }
            set {
                this["SaveThisStuff"] = value;
            }
        }
    }
}
